# See more config options https://book.getfoundry.sh/config/
[profile.default]
# project
src = 'src'
out = 'out'

# solc
solc_version = '0.8.26'
evm_version = "cancun"
# fmt
[fmt]
multiline_func_header = 'all'
number_underscore = 'thousands'
wrap_comments = true


[dependencies]
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"
forge-std = "1.9.1"
